# Default merchandise data extracted from Excel sheets

RORO_ITEMS = [
    {"marchandise": "VHL LEGER",                    "surface_per_unit": 8.00},
    {"marchandise": "CAMIONETTE H100/K2700/DFSK",   "surface_per_unit": 12.00},
    {"marchandise": "CAMION JMC/JAC/YUEGIN/HINO",   "surface_per_unit": 18.00},
    {"marchandise": "FOURGON",                       "surface_per_unit": 18.00},
    {"marchandise": "BUS 50 PLACES",                 "surface_per_unit": 40.00},
    {"marchandise": "BUS 35 PLACES",                 "surface_per_unit": 24.00},
    {"marchandise": "BUS 25 PLACES",                 "surface_per_unit": 18.00},
    {"marchandise": "CAMOINS DIVERS",                "surface_per_unit": 24.00},
    {"marchandise": "CAMION TRACTEUR",               "surface_per_unit": 18.00},
    {"marchandise": "CAMION POMPE",                  "surface_per_unit": 36.00},
    {"marchandise": "REMORQUE",                      "surface_per_unit": 24.00},
    {"marchandise": "REMORQUE PORTE CHAR",           "surface_per_unit": 36.00},
    {"marchandise": "REMORQUE PORTE VHL",            "surface_per_unit": 40.00},
    {"marchandise": "CHARHEUR",                      "surface_per_unit": 24.00},
    {"marchandise": "EXCAVATEUR",                    "surface_per_unit": 24.00},
    {"marchandise": "BULDOZER",                      "surface_per_unit": 24.00},
    {"marchandise": "FINISHEUR",                     "surface_per_unit": 24.00},
    {"marchandise": "RETRO CHARGEUR",                "surface_per_unit": 18.00},
    {"marchandise": "COMPACTEUR",                    "surface_per_unit": 18.00},
    {"marchandise": "CHARIO ELEVATEUR 15 T ET PLUS", "surface_per_unit": 18.00},
    {"marchandise": "TRACTEUR AGRICOLE",             "surface_per_unit": 18.00},
    {"marchandise": "CHARIO ELEVATEUR MOIN DE 15 T", "surface_per_unit": 12.00},
    {"marchandise": "NIVELLEUSE",                    "surface_per_unit": 40.00},
    {"marchandise": "CAMION GRUE GRAND TONNAGE",     "surface_per_unit": 60.00},
    {"marchandise": "CAMION GRUE PETIT TONNAGE",     "surface_per_unit": 36.00},
    {"marchandise": "PELLE CHARGEUR",                "surface_per_unit": 4.00},
    {"marchandise": "CONTRE POID GRUE MOBILE",       "surface_per_unit": 3.00},
    {"marchandise": "CHOULEUR",                      "surface_per_unit": 5.00},
    {"marchandise": "COLIS",                         "surface_per_unit": 2.00},
]

MARCHANDISES_ITEMS = [
    {"marchandise": "CORNIERE 12 M",          "surface_per_unit": 1.19, "gerbage": 1},
    {"marchandise": "CORNIERE 6 M",           "surface_per_unit": 0.80, "gerbage": 1},
    {"marchandise": "FDX TUBES 2\" - 4\"",    "surface_per_unit": 6.00, "gerbage": 5},
    {"marchandise": "TUBES 9\"",              "surface_per_unit": 3.60, "gerbage": 8},
    {"marchandise": "TUBES 13\"",             "surface_per_unit": 4.80, "gerbage": 7},
    {"marchandise": "TUBES ENROBE 8\"",       "surface_per_unit": 3.00, "gerbage": 10},
    {"marchandise": "FDX TUBES ENROBE 6\"",   "surface_per_unit": 2.40, "gerbage": 6},
    {"marchandise": "FDX TUBES ENROBE 10\"",  "surface_per_unit": 3.60, "gerbage": 9},
    {"marchandise": "TUBES ENROBE 20\"",      "surface_per_unit": 6.00, "gerbage": 5},
    {"marchandise": "TUBES 24\"",             "surface_per_unit": 7.20, "gerbage": 5},
    {"marchandise": "FDX TUBES 8\"",          "surface_per_unit": 8.40, "gerbage": 5},
    {"marchandise": "BIG BAGS",               "surface_per_unit": 1.70, "gerbage": 2},
    {"marchandise": "BOBINES LAC <> 10T-12T", "surface_per_unit": 2.00, "gerbage": 2},
    {"marchandise": "BOBINES PPG <> 5T-7T",   "surface_per_unit": 1.20, "gerbage": 3},
    {"marchandise": "BOBINES PPG <> 8T-9T",   "surface_per_unit": 1.35, "gerbage": 2},
    {"marchandise": "BOBINES LAC <> 20T-30T", "surface_per_unit": 3.25, "gerbage": 1},
    {"marchandise": "BOBINES LAC <> 13T-15T", "surface_per_unit": 2.20, "gerbage": 18},
    {"marchandise": "BOBINES LAC <> 16T-19T", "surface_per_unit": 2.20, "gerbage": 1},
    {"marchandise": "CTP 1,22 x 2,44 T/P",   "surface_per_unit": 2.90, "gerbage": 6},
    {"marchandise": "1MDF 0,85 x 2,00 HG",   "surface_per_unit": 1.90, "gerbage": 8},
    {"marchandise": "MDF 1,22 x 2,44 HG",    "surface_per_unit": 2.90, "gerbage": 6},
    {"marchandise": "MDF GF T/P",             "surface_per_unit": 2.90, "gerbage": 3},
    {"marchandise": "MDF GF HG",              "surface_per_unit": 2.90, "gerbage": 5},
    {"marchandise": "MDF 3,66x1,80",          "surface_per_unit": 6.60, "gerbage": 6},
    {"marchandise": "POUTRELLE FORTE EPESSEUR","surface_per_unit": 9.60, "gerbage": 5},
    {"marchandise": "POUTRELLE MINCE EPESSEUR","surface_per_unit": 7.20, "gerbage": 8},
    {"marchandise": "TOLE 6M",                "surface_per_unit": 0.27, "gerbage": 1},
    {"marchandise": "TOLE 12M",               "surface_per_unit": 0.60, "gerbage": 1},
    {"marchandise": "TOLE 3M",                "surface_per_unit": 1.40, "gerbage": 1},
    {"marchandise": "conteneur 40 pieds",     "surface_per_unit": 30.00,"gerbage": 1},
    {"marchandise": "conteneur 20 pieds",     "surface_per_unit": 15.00,"gerbage": 1},
    {"marchandise": "fil machine",            "surface_per_unit": 2.25, "gerbage": 2},
]
